// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwce3R0TSDk2LRGP_zS73cjnznG2PFzeo',
    appId: '1:516891803398:web:d6210483d5caff0f452887',
    messagingSenderId: '516891803398',
    projectId: 'food-app-with-admin-panel-76d2',
    authDomain: 'food-app-with-admin-panel-76d2.firebaseapp.com',
    storageBucket: 'food-app-with-admin-panel-76d2.appspot.com',
    measurementId: 'G-WN5E45W9EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhtPdFYLnvNZC_WDAcleKcUCUWVwxTY40',
    appId: '1:516891803398:android:fe396171c0fb8d20452887',
    messagingSenderId: '516891803398',
    projectId: 'food-app-with-admin-panel-76d2',
    storageBucket: 'food-app-with-admin-panel-76d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYgUJdUeuIzM7FgR7cqwf-hMcZsRVR_Ug',
    appId: '1:516891803398:ios:83ff2094e34c4676452887',
    messagingSenderId: '516891803398',
    projectId: 'food-app-with-admin-panel-76d2',
    storageBucket: 'food-app-with-admin-panel-76d2.appspot.com',
    androidClientId: '516891803398-djummobk3g72lbd9c1baaci4tou86s31.apps.googleusercontent.com',
    iosClientId: '516891803398-fh41fb9joua3na9okq4a1q4p9qd9mf07.apps.googleusercontent.com',
    iosBundleId: 'com.example.veggie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYgUJdUeuIzM7FgR7cqwf-hMcZsRVR_Ug',
    appId: '1:516891803398:ios:640d117662dabc8b452887',
    messagingSenderId: '516891803398',
    projectId: 'food-app-with-admin-panel-76d2',
    storageBucket: 'food-app-with-admin-panel-76d2.appspot.com',
    androidClientId: '516891803398-djummobk3g72lbd9c1baaci4tou86s31.apps.googleusercontent.com',
    iosClientId: '516891803398-3fmf3at9kof2v6upq28gj5oq91bo3l1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.veggie.RunnerTests',
  );
}
